### PR TITLE
Further type fixes

### LINKED ISSUE #14: [Bug]: Pimcore 11 incompatibility
### Expected behavior

 <br />
<b>Fatal error</b>:  Declaration of Pimcore\Bundle commerceFrameworkBundle\PaymentManager\Payment\PayPalSmartPaymentButton::handleResponse(Pimcore\Bundle commerceFrameworkBundle\PaymentManager\StatusInterface $response): Pimcore\Bundle commerceFrameworkBundle\PaymentManager\StatusInterface must be compatible with Pimcore\Bundle commerceFrameworkBundle\PaymentManager\V7\Payment\PaymentInterface::handleResponse(Pimcore\Bundle commerceFrameworkBundle\PaymentManager\StatusInterface|array $response): Pimcore\Bundle commerceFrameworkBundle\PaymentManager\StatusInterface in <b>/var/www/html/vendor/pimcore/payment-provider-paypal-smart-payment-button/src/PaymentManager/Payment/PayPalSmartPaymentButton.php</b> on line <b>192</b><br />

### Actual behavior

...

### Steps to reproduce

...

### PR DESCRIPTION
**Pull request by fashxp**
followup to #8 

Related to https://github.com/pimcore/pimcore/pull/13705/files#diff-6ae5becdc29ed2bfd963cb7834f25507665dc5cb64163b1e249b9bda4a959989R47

### CODE REVIEW

File: src/PaymentManager/Payment/PayPalSmartPaymentButton.php [hunk 1]
```diff
@@ -185,11 +185,11 @@ public function startPayment(OrderAgentInterface $orderAgent, PriceInterface $pr
     /**
      * Handles response of payment provider and creates payment status object
      *
-     * @param StatusInterface $response
+     * @param mixed $response
      *
      * @return StatusInterface
      */
-    public function handleResponse(StatusInterface $response): StatusInterface
+    public function handleResponse(mixed $response): StatusInterface
```
Comment (kingjia90) [inline src/PaymentManager/Payment/PayPalSmartPaymentButton.php]: Looks like could be narrowed down to
```suggestion
    public function handleResponse(StatusInterface|array $response): StatusInterface
```

See `$paymentResponseParams` : https://github.com/pimcore/pimcore/blob/2b964d491f9d91cc7794357358861eaeed611919/bundles/EcommerceFrameworkBundle/src/CheckoutManager/V7/CommitOrderProcessor.php#L95-L106

File: src/PaymentManager/Payment/PayPalSmartPaymentButton.php [hunk 2]
```diff
@@ -185,11 +185,11 @@ public function startPayment(OrderAgentInterface $orderAgent, PriceInterface $pr
     /**
      * Handles response of payment provider and creates payment status object
      *
-     * @param StatusInterface $response
+     * @param mixed $response
      *
      * @return StatusInterface
```
Comment (kingjia90) [inline src/PaymentManager/Payment/PayPalSmartPaymentButton.php]: We actually can remove the phpdoc block in this PR
The fix would be applied in https://github.com/pimcore/payment-provider-paypal-smart-payment-button/pull/13
